FROM --platform=linux/amd64 node:18-alpine as build

WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies for linux/amd64
RUN npm install --platform=linuxmusl --arch=x64

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Production environment
FROM --platform=linux/amd64 nginx:alpine

COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Copy nginx configuration if you have any custom config
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
