version: "3.8"

services:
  backend:
    platform: linux/amd64
    build:
      context: ./auction-api
      dockerfile: Dockerfile
      args:
        - PLATFORM=linux/amd64
    ports:
      - "3030:3030"
    volumes:
      - ./auction-api:/usr/src/app
      - /usr/src/app/node_modules # Anonymous volume for node_modules
    environment:
      - NODE_ENV=development
    command: ["node", "app.js"]

  frontend:
    platform: linux/amd64
    build:
      context: ./auction-app
      dockerfile: Dockerfile
      args:
        - PLATFORM=linux/amd64
    ports:
      - "3000:80"
    depends_on:
      - backend
